import os
import re
from datetime import datetime
from github import Github, GithubException


def build_branch_name(pillar: str, page_url: str) -> str:
    pillar_slug = re.sub(r'[^a-z0-9]', '-', pillar.lower()).strip('-')
    date_str = datetime.now().strftime("%Y-%m-%d")
    return f"vv-audit-{pillar_slug}-{date_str}"


def build_pr_body(pillar: str, page_url: str, issue: str,
                  before_text: str, after_text: str) -> str:
    return f"""## GEO Audit Fix — {pillar}

**Page:** {page_url}
**Issue:** {issue}

### Before
```
{before_text}
```

### After
```
{after_text}
```

---
*Generated by Victory Velocity GEO Audit System*"""


def apply_github_change(card: dict, cms_config: dict) -> dict:
    """Create a GitHub PR with the card's changes. Returns status dict."""
    token = cms_config.get("token") or os.environ.get("GITHUB_TOKEN", "")
    repo_name = cms_config.get("repo", "")
    if not token or not repo_name:
        return {"status": "error", "error": "GitHub token or repo not configured"}

    file_path = cms_config.get("content_path", "")
    if not file_path:
        return {"status": "error", "error": "No content_path configured — set the path to the content file in GitHub config"}

    try:
        return _create_pr(card, token, repo_name, file_path)
    except Exception as e:
        return {"status": "error", "error": str(e)}


def _create_pr(card: dict, token: str, repo_name: str, file_path: str) -> dict:
    g = Github(token)
    repo = g.get_repo(repo_name)

    file_content = repo.get_contents(file_path)
    current_content = file_content.decoded_content.decode("utf-8")

    if card["before_text"] and card["before_text"] in current_content:
        new_content = current_content.replace(card["before_text"], card["after_text"], 1)
    elif card["code_block"]:
        if "</head>" in current_content:
            new_content = current_content.replace(
                "</head>",
                f'<script type="application/ld+json">\n{card["code_block"]}\n</script>\n</head>',
                1
            )
        else:
            new_content = current_content + f'\n<script type="application/ld+json">\n{card["code_block"]}\n</script>'
    else:
        raise ValueError("Cannot apply card: before_text not found in file and no code_block present")

    branch_name = build_branch_name(card["pillar"], card["page_url"])

    main_branch = repo.get_branch(repo.default_branch)
    try:
        repo.create_git_ref(f"refs/heads/{branch_name}", main_branch.commit.sha)
    except GithubException as e:
        if e.status != 422:
            raise

    repo.update_file(
        path=file_path,
        message=f"fix(geo): improve {card['pillar'].lower()} — {card['issue'][:60]}",
        content=new_content,
        sha=file_content.sha,
        branch=branch_name,
    )

    pr = repo.create_pull(
        title=f"GEO: {card['pillar']} fix on {card['page_url'].split('/')[-1] or 'homepage'}",
        body=build_pr_body(
            pillar=card["pillar"],
            page_url=card["page_url"],
            issue=card["issue"],
            before_text=card.get("before_text", ""),
            after_text=card.get("after_text", ""),
        ),
        head=branch_name,
        base=repo.default_branch,
    )

    return {"status": "implemented", "pr_url": pr.html_url}
